# Configurações do banco de dados Oracle
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: usuario
    password: senha
    driver-class-name: oracle.jdbc.OracleDriver

# Configurações do JPA
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
    show-sql: true